In [21]:
import pandas as pd
import matplotlib as plt
import numpy as np
import requests
import gmaps

from config import api_key
# Census & gmaps API Keys
from config1 import (api_key, gkey)


# Configure gmaps
gmaps.configure(api_key=gkey)

In [22]:
#import world happyness data
happiness_data2015=pd.read_csv("Resources/happiness/2015.csv")

happiness_data2015_df=happiness_data2015.loc[:,["Country","Happiness Score","Happiness Rank"]]
happiness_data2015_df.head()

       Country  Happiness Score  Happiness Rank
0  Switzerland            7.587               1
1      Iceland            7.561               2
2      Denmark            7.527               3
3       Norway            7.522               4
4       Canada            7.427               5

In [23]:
# put city name in a list
countries=happiness_data2015_df["Country"].tolist()

lat=[]
lng=[]
shortname=[]
i=1
for country in countries:
        target_url = ('https://maps.googleapis.com/maps/api/geocode/json?''address={0}&key={1}').format(country, gkey)
        response = requests.get(target_url).json()
        print("Processing Record " + str(i) + " of Set 1 | " + country)
        shortname.append(response['results'][0]['address_components'][0]['short_name'])
        lat.append(response['results'][0]['geometry']['location']["lat"])
        lng.append(response['results'][0]['geometry']['location']["lng"])
        i=i+1

Processing Record 1 of Set 1 | Switzerland
Processing Record 2 of Set 1 | Iceland
Processing Record 3 of Set 1 | Denmark
Processing Record 4 of Set 1 | Norway
Processing Record 5 of Set 1 | Canada
Processing Record 6 of Set 1 | Finland
Processing Record 7 of Set 1 | Netherlands
Processing Record 8 of Set 1 | Sweden
Processing Record 9 of Set 1 | New Zealand
Processing Record 10 of Set 1 | Australia
Processing Record 11 of Set 1 | Israel
Processing Record 12 of Set 1 | Costa Rica
Processing Record 13 of Set 1 | Austria
Processing Record 14 of Set 1 | Mexico
Processing Record 15 of Set 1 | United States
Processing Record 16 of Set 1 | Brazil
Processing Record 17 of Set 1 | Luxembourg
Processing Record 18 of Set 1 | Ireland
Processing Record 19 of Set 1 | Belgium
Processing Record 20 of Set 1 | United Arab Emirates
Processing Record 21 of Set 1 | United Kingdom
Processing Record 22 of Set 1 | Oman
Processing Record 23 of Set 1 | Venezuela
Processing Record 24 of Set 1 | Singapore
Processing Record 25 of Set 1 | Panama
Processing Record 26 of Set 1 | Germany
Processing Record 27 of Set 1 | Chile
Processing Record 28 of Set 1 | Qatar
Processing Record 29 of Set 1 | France
Processing Record 30 of Set 1 | Argentina
Processing Record 31 of Set 1 | Czech Republic
Processing Record 32 of Set 1 | Uruguay
Processing Record 33 of Set 1 | Colombia
Processing Record 34 of Set 1 | Thailand
Processing Record 35 of Set 1 | Saudi Arabia
Processing Record 36 of Set 1 | Spain
Processing Record 37 of Set 1 | Malta
Processing Record 38 of Set 1 | Taiwan
Processing Record 39 of Set 1 | Kuwait
Processing Record 40 of Set 1 | Suriname
Processing Record 41 of Set 1 | Trinidad and Tobago
Processing Record 42 of Set 1 | El Salvador
Processing Record 43 of Set 1 | Guatemala
Processing Record 44 of Set 1 | Uzbekistan
Processing Record 45 of Set 1 | Slovakia
Processing Record 46 of Set 1 | Japan
Processing Record 47 of Set 1 | South Korea
Processing Record 48 of Set 1 | Ecuador
Processing Record 49 of Set 1 | Bahrain
Processing Record 50 of Set 1 | Italy
Processing Record 51 of Set 1 | Bolivia
Processing Record 52 of Set 1 | Moldova
Processing Record 53 of Set 1 | Paraguay
Processing Record 54 of Set 1 | Kazakhstan
Processing Record 55 of Set 1 | Slovenia
Processing Record 56 of Set 1 | Lithuania
Processing Record 57 of Set 1 | Nicaragua
Processing Record 58 of Set 1 | Peru
Processing Record 59 of Set 1 | Belarus
Processing Record 60 of Set 1 | Poland
Processing Record 61 of Set 1 | Malaysia
Processing Record 62 of Set 1 | Croatia
Processing Record 63 of Set 1 | Libya
Processing Record 64 of Set 1 | Russia
Processing Record 65 of Set 1 | Jamaica
Processing Record 66 of Set 1 | North Cyprus
Processing Record 67 of Set 1 | Cyprus
Processing Record 68 of Set 1 | Algeria
Processing Record 69 of Set 1 | Kosovo
Processing Record 70 of Set 1 | Turkmenistan
Processing Record 71 of Set 1 | Mauritius
Processing Record 72 of Set 1 | Hong Kong
Processing Record 73 of Set 1 | Estonia
Processing Record 74 of Set 1 | Indonesia
Processing Record 75 of Set 1 | Vietnam
Processing Record 76 of Set 1 | Turkey
Processing Record 77 of Set 1 | Kyrgyzstan
Processing Record 78 of Set 1 | Nigeria
Processing Record 79 of Set 1 | Bhutan
Processing Record 80 of Set 1 | Azerbaijan
Processing Record 81 of Set 1 | Pakistan
Processing Record 82 of Set 1 | Jordan
Processing Record 83 of Set 1 | Montenegro
Processing Record 84 of Set 1 | China
Processing Record 85 of Set 1 | Zambia
Processing Record 86 of Set 1 | Romania
Processing Record 87 of Set 1 | Serbia
Processing Record 88 of Set 1 | Portugal
Processing Record 89 of Set 1 | Latvia
Processing Record 90 of Set 1 | Philippines
Processing Record 91 of Set 1 | Somaliland region
Processing Record 92 of Set 1 | Morocco
Processing Record 93 of Set 1 | Macedonia
Processing Record 94 of Set 1 | Mozambique
Processing Record 95 of Set 1 | Albania
Processing Record 96 of Set 1 | Bosnia and Herzegovina
Processing Record 97 of Set 1 | Lesotho
Processing Record 98 of Set 1 | Dominican Republic
Processing Record 99 of Set 1 | Laos
Processing Record 100 of Set 1 | Mongolia
Processing Record 101 of Set 1 | Swaziland
Processing Record 102 of Set 1 | Greece
Processing Record 103 of Set 1 | Lebanon
Processing Record 104 of Set 1 | Hungary
Processing Record 105 of Set 1 | Honduras
Processing Record 106 of Set 1 | Tajikistan
Processing Record 107 of Set 1 | Tunisia
Processing Record 108 of Set 1 | Palestinian Territories
Processing Record 109 of Set 1 | Bangladesh
Processing Record 110 of Set 1 | Iran
Processing Record 111 of Set 1 | Ukraine
Processing Record 112 of Set 1 | Iraq
Processing Record 113 of Set 1 | South Africa
Processing Record 114 of Set 1 | Ghana
Processing Record 115 of Set 1 | Zimbabwe
Processing Record 116 of Set 1 | Liberia
Processing Record 117 of Set 1 | India
Processing Record 118 of Set 1 | Sudan
Processing Record 119 of Set 1 | Haiti
Processing Record 120 of Set 1 | Congo (Kinshasa)
Processing Record 121 of Set 1 | Nepal
Processing Record 122 of Set 1 | Ethiopia
Processing Record 123 of Set 1 | Sierra Leone
Processing Record 124 of Set 1 | Mauritania
Processing Record 125 of Set 1 | Kenya
Processing Record 126 of Set 1 | Djibouti
Processing Record 127 of Set 1 | Armenia
Processing Record 128 of Set 1 | Botswana
Processing Record 129 of Set 1 | Myanmar
Processing Record 130 of Set 1 | Georgia
Processing Record 131 of Set 1 | Malawi
Processing Record 132 of Set 1 | Sri Lanka
Processing Record 133 of Set 1 | Cameroon
Processing Record 134 of Set 1 | Bulgaria
Processing Record 135 of Set 1 | Egypt
Processing Record 136 of Set 1 | Yemen
Processing Record 137 of Set 1 | Angola
Processing Record 138 of Set 1 | Mali
Processing Record 139 of Set 1 | Congo (Brazzaville)
Processing Record 140 of Set 1 | Comoros
Processing Record 141 of Set 1 | Uganda
Processing Record 142 of Set 1 | Senegal
Processing Record 143 of Set 1 | Gabon
Processing Record 144 of Set 1 | Niger
Processing Record 145 of Set 1 | Cambodia
Processing Record 146 of Set 1 | Tanzania
Processing Record 147 of Set 1 | Madagascar
Processing Record 148 of Set 1 | Central African Republic
Processing Record 149 of Set 1 | Chad
Processing Record 150 of Set 1 | Guinea
Processing Record 151 of Set 1 | Ivory Coast
Processing Record 152 of Set 1 | Burkina Faso
Processing Record 153 of Set 1 | Afghanistan
Processing Record 154 of Set 1 | Rwanda
Processing Record 155 of Set 1 | Benin
Processing Record 156 of Set 1 | Syria
Processing Record 157 of Set 1 | Burundi
Processing Record 158 of Set 1 | Togo

In [24]:
#add lat and lng to the happyness dataframe
happiness_data2015_df["Lat"]=lat
happiness_data2015_df["Lng"]=lng
happiness_data2015_df['Short Name']=shortname

In [25]:
# select top 20 happiness country and store top20 maker location for lat, lng
top20=happiness_data2015_df.loc[happiness_data2015_df["Happiness Rank"]<21]
top20_marker_locations =top20[["Lat","Lng"]]
top20_countries=top20["Country"]
top20

,Country,Happiness Score,Happiness Rank,Lat,Lng,Short Name
0,Switzerland,7.587,1,46.818188,8.227512,CH
1,Iceland,7.561,2,64.963051,-19.020835,IS
2,Denmark,7.527,3,56.263920,9.501785,DK
3,Norway,7.522,4,60.472024,8.468946,NO
4,Canada,7.427,5,56.130366,-106.346771,CA
5,Finland,7.406,6,61.924110,25.748151,FI
6,Netherlands,7.378,7,52.132633,5.291266,NL
7,Sweden,7.364,8,60.128161,18.643501,SE
8,New Zealand,7.286,9,-40.900557,174.885971,NZ
9,Australia,7.284,10,-25.274398,133.775136,AU
10,Israel,7.278,11,31.046051,34.851612,IL
11,Costa Rica,7.226,12,9.748917,-83.753428,CR
12,Austria,7.200,13,47.516231,14.550072,AT
13,Mexico,7.187,14,23.634501,-102.552784,MX
14,United States,7.119,15,37.090240,-95.712891,US
15,Brazil,6.983,16,-14.235004,-51.925280,BR
16,Luxembourg,6.946,17,49.815273,6.129583,LU
17,Ireland,6.940,18,53.142367,-7.692054,Ireland
18,Belgium,6.937,19,50.503887,4.469936,BE
19,United Arab Emirates,6.901,20,23.424076,53.847818,AE

In [26]:
# Create a map using top20 Happiness country coordinates to set markers
# Create a marker_layer using the top20 country name list to fill the info box
fig1 = gmaps.figure()
markers1 = gmaps.marker_layer(top20_marker_locations,info_box_content=[f"Country: {country}" for country in top20_countries])
fig1.add_layer(markers1)

fig1

Figure(layout=FigureLayout(height='420px'))

In [27]:
# select low 20 happiness country and store low 20 maker location for lat, lng
low20=happiness_data2015_df.loc[happiness_data2015_df["Happiness Rank"]>137]
low20_marker_locations =low20[["Lat","Lng"]]
low20_countries=low20["Country"]

In [28]:
# Create a map using low20 Happiness country coordinates to set markers
# Create a marker_layer using the low20 country name list to fill the info box
fig2 = gmaps.figure()
markers2 = gmaps.marker_layer(low20_marker_locations,info_box_content=[f"Country: {country}" for country in low20_countries])
fig2.add_layer(markers2)
fig2

Figure(layout=FigureLayout(height='420px'))

In [240]:
#import world current health expenditure data set from csv file and organized the data for analysis
health_current_expenditure = pd.read_csv("Resources/current_expenditure_Data.csv")
health_current_expenditure_2015=health_current_expenditure.loc[:,["Country Name","2015 [YR2015]"]]
health_current_expenditure_2015=health_current_expenditure_2015.rename(columns={"2015 [YR2015]":"2015 Current Health Expediture (%GDP)",
                                                                       "Country Name":"Country"})
#import world domestic govement health expenditure data set from csv file and organized the data for analysis
health_gov_expenditure=pd.read_csv("Resources/Domestic_Govement_Health_Expenditure Data.csv")
health_gov_expenditure_2015=health_gov_expenditure.loc[:,["Country Name","2015 [YR2015]"]]
health_gov_expenditure_2015=health_gov_expenditure_2015.rename(columns={"2015 [YR2015]":"2015 govement Health Expediture (%GDP)",
                                                                       "Country Name":"Country"})

In [241]:
merge1=happiness_data2015_df.merge(health_current_expenditure_2015,on='Country',how="left")
merge2=merge1.merge(health_gov_expenditure_2015,on='Country',how="left")

merge2.count()

Country                                   158
Happiness Score                           158
Happiness Rank                            158
Lat                                       158
Lng                                       158
Short Name                                158
2015 Current Health Expediture (%GDP)     138
2015 govement Health Expediture (%GDP)    138
dtype: int64

In [242]:
#import world out of pocket expediture
import json 

#oop_url="http://apps.who.int/gho/athena/data/GHO/GHED_OOP_pc_US_SHA2011.json?profile=simple&filter=COUNTRY:*;YEAR:2015"
oop_url="http://apps.who.int/gho/athena/data/GHO/GHED_OOPSCHE_SHA2011.json?profile=simple&filter=COUNTRY:*;YEAR:2015"
response_OOP = requests.get(oop_url).json()

total=np.arange(0,194,1)
oop_value=[]
oop_country=[]

i=0
for i in total:
    oop_country.append(response_OOP['fact'][i]['dim']["COUNTRY"])
    oop_value.append(response_OOP['fact'][i]['Value'])
    i=i+1

In [244]:
#Merge oop_data to final dataframe
oop_data=pd.DataFrame({"Country":oop_country,
                       "OOP/CHE(%)":oop_value})
final_health_data=merge2.merge(oop_data,on='Country',how="left")
final_health_data

,Country,Happiness Score,Happiness Rank,Lat,Lng,Short Name,2015 Current Health Expediture (%GDP),2015 govement Health Expediture (%GDP),OOP/CHE(%)
0,Switzerland,7.587,1,46.818188,8.227512,CH,12.05701692,70.72655713,28.3
1,Iceland,7.561,2,64.963051,-19.020835,IS,8.6091496,81.47514535,17.0
2,Denmark,7.527,3,56.263920,9.501785,DK,10.32620701,84.14279942,13.7
3,Norway,7.522,4,60.472024,8.468946,NO,9.97554719,85.39754712,14.3
4,Canada,7.427,5,56.130366,-106.346771,CA,10.43562237,73.54982557,14.6
5,Finland,7.406,6,61.924110,25.748151,FI,9.44569068,77.41248113,19.9
6,Netherlands,7.378,7,52.132633,5.291266,NL,10.6902779,80.71063836,12.3
7,Sweden,7.364,8,60.128161,18.643501,SE,11.01207026,83.66360718,15.2
8,New Zealand,7.286,9,-40.900557,174.885971,NZ,9.34035114,..,0.0
9,Australia,7.284,10,-25.274398,133.775136,AU,9.44533327,..,No data
10,Israel,7.278,11,31.046051,34.851612,IL,7.4313808,..,24.4
11,Costa Rica,7.226,12,9.748917,-83.753428,CR,8.14558457,75.96967363,21.5
12,Austria,7.200,13,47.516231,14.550072,AT,10.31988167,75.58406305,17.9
13,Mexico,7.187,14,23.634501,-102.552784,MX,5.86449037,52.16868492,41.4
14,United States,7.119,15,37.090240,-95.712891,US,16.83613019,50.35616434,NaN
15,Brazil,6.983,16,-14.235004,-51.925280,BR,8.91148377,42.75367468,28.3
16,Luxembourg,6.946,17,49.815273,6.129583,LU,6.04774196,82.67472681,10.6
17,Ireland,6.940,18,53.142367,-7.692054,Ireland,7.76144215,69.98817926,15.2
18,Belgium,6.937,19,50.503887,4.469936,BE,10.47712841,82.40462397,17.6
19,United Arab Emirates,6.901,20,23.424076,53.847818,AE,3.46589995,71.25105548,17.8
20,United Kingdom,6.867,21,55.378051,-3.435973,GB,9.87677211,80.35156024,NaN
21,Oman,6.853,22,21.473533,55.975413,OM,3.82790443,88.25362722,6.4
22,Venezuela,6.810,23,6.423750,-66.589730,VE,NaN,NaN,NaN
23,Singapore,6.798,24,1.352083,103.819836,SG,4.25217534,51.87575635,36.7
24,Panama,6.786,25,8.537981,-80.782127,PA,7.00916167,61.58047485,30.5
25,Germany,6.750,26,51.165691,10.451526,DE,11.15156851,84.47016176,12.5
26,Chile,6.670,27,-35.675147,-71.542969,CL,8.07108586,60.78119408,32.2
27,Qatar,6.611,28,25.354826,51.183884,QA,3.05900331,85.41249059,6.2
28,France,6.575,29,46.227638,2.213749,FR,11.0664428,78.92436191,6.8
29,Argentina,6.574,30,-38.416097,-63.616672,AR,6.83453274,71.41693017,17.6
...,...,...,...,...,...,...,...,...,...
128,Myanmar,4.307,129,21.916221,95.955974,MM,4.94925346,23.00182011,73.9
129,Georgia,4.297,130,32.165622,-82.900075,GA,7.93235924,38.78523224,57.3
130,Malawi,4.292,131,-13.254308,34.301525,MW,9.33097184,28.64990369,11.0
131,Sri Lanka,4.271,132,7.873054,80.771797,LK,2.96601516,53.71800995,38.4
132,Cameroon,4.252,133,7.369722,12.354722,CM,5.11302542,14.4602271,69.7
133,Bulgaria,4.218,134,42.733883,25.485830,BG,8.20309288,51.08709745,47.7
134,Egypt,4.194,135,26.820553,30.802498,EG,NaN,NaN,62.0
135,Yemen,4.077,136,15.552727,48.516388,YE,NaN,NaN,81.0
136,Angola,4.033,137,-11.202692,17.873887,AO,2.94697845,47.50627957,33.4
137,Mali,3.995,138,17.570692,-3.996166,ML,5.79663385,16.54630036,46.3
138,Congo (Brazzaville),3.989,139,-4.263360,15.242885,Brazzaville,NaN,NaN,NaN
139,Comoros,3.956,140,-11.645500,43.333300,KM,8.04626019,13.40060749,74.8
140,Uganda,3.931,141,1.373333,32.290275,UG,7.30193117,13.43168492,40.5
141,Senegal,3.904,142,14.497401,-14.452362,SN,3.97026571,31.74941378,44.2
142,Gabon,3.896,143,-0.803689,11.609444,GA,2.67891653,58.90986608,25.9
143,Niger,3.845,144,17.607789,8.081666,NE,7.1651979,21.02340571,52.3
144,Cambodia,3.819,145,12.565679,104.990963,KH,5.98226009,20.85967638,59.4
145,Tanzania,3.781,146,-6.369028,34.888822,TZ,6.12306537,35.30276984,NaN
146,Madagascar,3.681,147,-18.766947,46.869107,MG,5.23778965,45.15438957,21.7
147,Central African Republic,3.678,148,6.611111,20.939444,CF,4.77627738,12.76758909,39.6
148,Chad,3.667,149,15.454166,18.732207,TD,4.57628264,23.46268231,56.4
149,Guinea,3.656,150,9.945587,-9.696645,GN,4.53653174,17.14846216,54.5
150,Ivory Coast,3.655,151,7.539989,-5.547080,CI,NaN,NaN,NaN
151,Burkina Faso,3.587,152,12.238333,-1.561593,BF,5.446772,28.24113204,36.1
152,Afghanistan,3.575,153,33.939110,67.709953,AF,10.29759481,5.17223951,78.4
153,Rwanda,3.465,154,-1.940278,29.873888,RW,7.89529324,21.37426684,26.0
154,Benin,3.340,155,9.307690,2.315834,BJ,3.99190103,20.13637677,40.5
155,Syria,3.006,156,34.802075,38.996815,SY,NaN,NaN,NaN
156,Burundi,2.905,157,-3.373056,29.918886,BI,8.24294928,38.81822708,19.1
157,Togo,2.839,158,8.619543,0.824782,TG,6.64913046,28.00110238,51.0

'151.4'