In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
import requests
from census import Census
import gmaps
#config
from config import api_key

# Census & gmaps API Keys
from config1 import (api_key, gkey)
c = Census(api_key, year=2015)

# Configure gmaps
gmaps.configure(api_key=gkey)

In [3]:
#import world happyness data
happiness_data2015=pd.read_csv("Resources/happiness/2015.csv")

happiness_data2015_df=happiness_data2015.loc[:,["Country","Happiness Score","Happiness Rank"]]
happiness_data2015_df.head()

       Country  Happiness Score  Happiness Rank
0  Switzerland            7.587               1
1      Iceland            7.561               2
2      Denmark            7.527               3
3       Norway            7.522               4
4       Canada            7.427               5

In [4]:
# put city name in a list
countries=happiness_data2015_df["Country"].tolist()
# get weather information for each country
url = "http://api.openweathermap.org/data/2.5/weather?"
units = "metric"
#query_url = f"{url}appid=423160d06ea84b634174ef9038841d0f&units={units}&q="


lat=[]
lng=[]
shortname=[]
i=1
for country in countries:
        target_url = ('https://maps.googleapis.com/maps/api/geocode/json?''address={0}&key={1}').format(country, gkey)
        response = requests.get(target_url).json()
        print("Processing Record " + str(i) + " of Set 1 | " + country)
        shortname.append(response['results'][0]['address_components'][0]['short_name'])
        lat.append(response['results'][0]['geometry']['location']["lat"])
        lng.append(response['results'][0]['geometry']['location']["lng"])
        i=i+1

Processing Record 1 of Set 1 | Switzerland
Processing Record 2 of Set 1 | Iceland
Processing Record 3 of Set 1 | Denmark
Processing Record 4 of Set 1 | Norway
Processing Record 5 of Set 1 | Canada
Processing Record 6 of Set 1 | Finland
Processing Record 7 of Set 1 | Netherlands
Processing Record 8 of Set 1 | Sweden
Processing Record 9 of Set 1 | New Zealand
Processing Record 10 of Set 1 | Australia
Processing Record 11 of Set 1 | Israel
Processing Record 12 of Set 1 | Costa Rica
Processing Record 13 of Set 1 | Austria
Processing Record 14 of Set 1 | Mexico
Processing Record 15 of Set 1 | United States
Processing Record 16 of Set 1 | Brazil
Processing Record 17 of Set 1 | Luxembourg
Processing Record 18 of Set 1 | Ireland
Processing Record 19 of Set 1 | Belgium
Processing Record 20 of Set 1 | United Arab Emirates
Processing Record 21 of Set 1 | United Kingdom
Processing Record 22 of Set 1 | Oman
Processing Record 23 of Set 1 | Venezuela
Processing Record 24 of Set 1 | Singapore
Processing Record 25 of Set 1 | Panama
Processing Record 26 of Set 1 | Germany
Processing Record 27 of Set 1 | Chile
Processing Record 28 of Set 1 | Qatar
Processing Record 29 of Set 1 | France
Processing Record 30 of Set 1 | Argentina
Processing Record 31 of Set 1 | Czech Republic
Processing Record 32 of Set 1 | Uruguay
Processing Record 33 of Set 1 | Colombia
Processing Record 34 of Set 1 | Thailand
Processing Record 35 of Set 1 | Saudi Arabia
Processing Record 36 of Set 1 | Spain
Processing Record 37 of Set 1 | Malta
Processing Record 38 of Set 1 | Taiwan
Processing Record 39 of Set 1 | Kuwait
Processing Record 40 of Set 1 | Suriname
Processing Record 41 of Set 1 | Trinidad and Tobago
Processing Record 42 of Set 1 | El Salvador
Processing Record 43 of Set 1 | Guatemala
Processing Record 44 of Set 1 | Uzbekistan
Processing Record 45 of Set 1 | Slovakia
Processing Record 46 of Set 1 | Japan
Processing Record 47 of Set 1 | South Korea
Processing Record 48 of Set 1 | Ecuador
Processing Record 49 of Set 1 | Bahrain
Processing Record 50 of Set 1 | Italy
Processing Record 51 of Set 1 | Bolivia
Processing Record 52 of Set 1 | Moldova
Processing Record 53 of Set 1 | Paraguay
Processing Record 54 of Set 1 | Kazakhstan
Processing Record 55 of Set 1 | Slovenia
Processing Record 56 of Set 1 | Lithuania
Processing Record 57 of Set 1 | Nicaragua
Processing Record 58 of Set 1 | Peru
Processing Record 59 of Set 1 | Belarus
Processing Record 60 of Set 1 | Poland
Processing Record 61 of Set 1 | Malaysia
Processing Record 62 of Set 1 | Croatia
Processing Record 63 of Set 1 | Libya
Processing Record 64 of Set 1 | Russia
Processing Record 65 of Set 1 | Jamaica
Processing Record 66 of Set 1 | North Cyprus
Processing Record 67 of Set 1 | Cyprus
Processing Record 68 of Set 1 | Algeria
Processing Record 69 of Set 1 | Kosovo
Processing Record 70 of Set 1 | Turkmenistan
Processing Record 71 of Set 1 | Mauritius
Processing Record 72 of Set 1 | Hong Kong
Processing Record 73 of Set 1 | Estonia
Processing Record 74 of Set 1 | Indonesia
Processing Record 75 of Set 1 | Vietnam
Processing Record 76 of Set 1 | Turkey
Processing Record 77 of Set 1 | Kyrgyzstan
Processing Record 78 of Set 1 | Nigeria
Processing Record 79 of Set 1 | Bhutan
Processing Record 80 of Set 1 | Azerbaijan
Processing Record 81 of Set 1 | Pakistan
Processing Record 82 of Set 1 | Jordan
Processing Record 83 of Set 1 | Montenegro
Processing Record 84 of Set 1 | China
Processing Record 85 of Set 1 | Zambia
Processing Record 86 of Set 1 | Romania
Processing Record 87 of Set 1 | Serbia
Processing Record 88 of Set 1 | Portugal
Processing Record 89 of Set 1 | Latvia
Processing Record 90 of Set 1 | Philippines
Processing Record 91 of Set 1 | Somaliland region
Processing Record 92 of Set 1 | Morocco
Processing Record 93 of Set 1 | Macedonia
Processing Record 94 of Set 1 | Mozambique
Processing Record 95 of Set 1 | Albania
Processing Record 96 of Set 1 | Bosnia and Herzegovina
Processing Record 97 of Set 1 | Lesotho
Processing Record 98 of Set 1 | Dominican Republic
Processing Record 99 of Set 1 | Laos
Processing Record 100 of Set 1 | Mongolia
Processing Record 101 of Set 1 | Swaziland
Processing Record 102 of Set 1 | Greece
Processing Record 103 of Set 1 | Lebanon
Processing Record 104 of Set 1 | Hungary
Processing Record 105 of Set 1 | Honduras
Processing Record 106 of Set 1 | Tajikistan
Processing Record 107 of Set 1 | Tunisia
Processing Record 108 of Set 1 | Palestinian Territories
Processing Record 109 of Set 1 | Bangladesh
Processing Record 110 of Set 1 | Iran
Processing Record 111 of Set 1 | Ukraine
Processing Record 112 of Set 1 | Iraq
Processing Record 113 of Set 1 | South Africa
Processing Record 114 of Set 1 | Ghana
Processing Record 115 of Set 1 | Zimbabwe
Processing Record 116 of Set 1 | Liberia
Processing Record 117 of Set 1 | India
Processing Record 118 of Set 1 | Sudan
Processing Record 119 of Set 1 | Haiti
Processing Record 120 of Set 1 | Congo (Kinshasa)
Processing Record 121 of Set 1 | Nepal
Processing Record 122 of Set 1 | Ethiopia
Processing Record 123 of Set 1 | Sierra Leone
Processing Record 124 of Set 1 | Mauritania
Processing Record 125 of Set 1 | Kenya
Processing Record 126 of Set 1 | Djibouti
Processing Record 127 of Set 1 | Armenia
Processing Record 128 of Set 1 | Botswana
Processing Record 129 of Set 1 | Myanmar
Processing Record 130 of Set 1 | Georgia
Processing Record 131 of Set 1 | Malawi
Processing Record 132 of Set 1 | Sri Lanka
Processing Record 133 of Set 1 | Cameroon
Processing Record 134 of Set 1 | Bulgaria
Processing Record 135 of Set 1 | Egypt
Processing Record 136 of Set 1 | Yemen
Processing Record 137 of Set 1 | Angola
Processing Record 138 of Set 1 | Mali
Processing Record 139 of Set 1 | Congo (Brazzaville)
Processing Record 140 of Set 1 | Comoros
Processing Record 141 of Set 1 | Uganda
Processing Record 142 of Set 1 | Senegal
Processing Record 143 of Set 1 | Gabon
Processing Record 144 of Set 1 | Niger
Processing Record 145 of Set 1 | Cambodia
Processing Record 146 of Set 1 | Tanzania
Processing Record 147 of Set 1 | Madagascar
Processing Record 148 of Set 1 | Central African Republic
Processing Record 149 of Set 1 | Chad
Processing Record 150 of Set 1 | Guinea
Processing Record 151 of Set 1 | Ivory Coast
Processing Record 152 of Set 1 | Burkina Faso
Processing Record 153 of Set 1 | Afghanistan
Processing Record 154 of Set 1 | Rwanda
Processing Record 155 of Set 1 | Benin
Processing Record 156 of Set 1 | Syria
Processing Record 157 of Set 1 | Burundi
Processing Record 158 of Set 1 | Togo

In [5]:
#add lat and lng to the happyness dataframe
happiness_data2015_df["Lat"]=lat
happiness_data2015_df["Lng"]=lng
happiness_data2015_df['Short Name']=shortname

In [6]:
top20=happiness_data2015_df.loc[happiness_data2015_df["Happiness Rank"]<21]
top20_marker_locations =top20[["Lat","Lng"]]
top20_countries=top20["Country"]
top20

,Country,Happiness Score,Happiness Rank,Lat,Lng,Short Name
0,Switzerland,7.587,1,46.818188,8.227512,CH
1,Iceland,7.561,2,64.963051,-19.020835,IS
2,Denmark,7.527,3,56.263920,9.501785,DK
3,Norway,7.522,4,60.472024,8.468946,NO
4,Canada,7.427,5,56.130366,-106.346771,CA
5,Finland,7.406,6,61.924110,25.748151,FI
6,Netherlands,7.378,7,52.132633,5.291266,NL
7,Sweden,7.364,8,60.128161,18.643501,SE
8,New Zealand,7.286,9,-40.900557,174.885971,NZ
9,Australia,7.284,10,-25.274398,133.775136,AU
10,Israel,7.278,11,31.046051,34.851612,IL
11,Costa Rica,7.226,12,9.748917,-83.753428,CR
12,Austria,7.200,13,47.516231,14.550072,AT
13,Mexico,7.187,14,23.634501,-102.552784,MX
14,United States,7.119,15,37.090240,-95.712891,US
15,Brazil,6.983,16,-14.235004,-51.925280,BR
16,Luxembourg,6.946,17,49.815273,6.129583,LU
17,Ireland,6.940,18,53.142367,-7.692054,Ireland
18,Belgium,6.937,19,50.503887,4.469936,BE
19,United Arab Emirates,6.901,20,23.424076,53.847818,AE

In [11]:
# Create a map using state centroid coordinates to set markers
#happiness=data2015_df["Happiness Rank"].tolist()
# Create a marker_layer using the poverty list to fill the info box
fig1 = gmaps.figure()
markers1 = gmaps.marker_layer(top20_marker_locations,info_box_content=[f"Country: {country}" for country in top20_countries])
fig1.add_layer(markers1)
fig1

Figure(layout=FigureLayout(height='420px'))

In [9]:
low20=happiness_data2015_df.loc[happiness_data2015_df["Happiness Rank"]>137]
low20_marker_locations =low20[["Lat","Lng"]]
low20_countries=low20["Country"]

In [10]:
fig2 = gmaps.figure()
markers2 = gmaps.marker_layer(low20_marker_locations,info_box_content=[f"Country: {country}" for country in low20_countries])
fig2.add_layer(markers2)
fig2

Figure(layout=FigureLayout(height='420px'))